import type {
  ExamType,
  InstitutionType,
  PerformanceSource,
  PriceSource,
} from '../src/generated/prisma/enums.js';

/**
 * ==========================================================================
 * EVERY INSTITUTION BELOW IS FICTIONAL.
 *
 * No real school, chain, teacher or exam statistic is represented here. Names,
 * addresses, phone numbers, prices and success figures were invented for
 * development and demo purposes. The UI carries a banner saying so, and it must
 * keep doing so for as long as this data is in the database.
 * ==========================================================================
 */

export interface SeedBranch {
  name: string;
  city: string;
  district: string;
  address: string;
  lat: number;
  lng: number;
  capacity: number;
}

export interface SeedProgram {
  name: string;
  examType: ExamType;
  targetGrade: string;
  weeklyHours: number;
  classSize: number;
  durationMonths: number;
  includesMaterials: boolean;
  includesEtut: boolean;
  /** Current-year list price in whole TRY. Earlier years are derived from it. */
  listPrice: number;
  /** Current-year discounted price, when the institution advertises one. */
  discountedPrice: number | null;
  installmentCount: number;
  priceSource: PriceSource;
  priceSourceNote: string;
}

export interface SeedPerformance {
  academicYear: string;
  examType: ExamType;
  studentCount: number | null;
  avgNetIncrease: number | null;
  top1000Count: number | null;
  /** Percentage, 0–100. */
  placementRate: number | null;
  source: PerformanceSource;
  sourceNote: string;
  /** Only OSYM_PUBLIC rows are verified; claims stay unverified on purpose. */
  verified: boolean;
}

export interface SeedInstitution {
  slug: string;
  name: string;
  brand: string | null;
  type: InstitutionType;
  description: string;
  foundedYear: number;
  website: string;
  phone: string;
  isVerified: boolean;
  branches: SeedBranch[];
  programs: SeedProgram[];
  performance: SeedPerformance[];
}

export const CURRENT_ACADEMIC_YEAR = '2024-2025';
export const PREVIOUS_ACADEMIC_YEAR = '2023-2024';

/** Author aliases for generated reviews — no real people. */
export const REVIEW_ALIASES = [
  'Mezun 2024',
  'Veli_34',
  'Sayısalcı Öğrenci',
  'EA Mezunu',
  'Anonim Veli',
  'LGS Velisi',
  'Eşit Ağırlık 2023',
  'Kursiyer',
  '12. Sınıf Öğrencisi',
  'Mezun Grubu',
  'Sözelci',
  'Veli (İki Çocuk)',
  'Dil Öğrencisi',
  'Tekrar Öğrencisi',
  'Yeni Kayıt Velisi',
];

/** Review bodies, paired with the rating band they are plausible for. */
export const REVIEW_BODIES: Record<'low' | 'mid' | 'high', string[]> = {
  low: [
    'Sınıflar tanıtımda söylenenden kalabalıktı, öğretmenle birebir ilgilenme fırsatı az oldu. Fiyatına göre beklentimi karşılamadı.',
    'Rehberlik servisi dönem ortasında değişti, takip kopukluğu yaşadık. Ders anlatımı fena değildi ama organizasyon zayıftı.',
    'Etüt saatleri duyurulduğu gibi işlemedi, birkaç kez boşa gidip geldik. Ücret iadesi konusunda da net bilgi alamadık.',
    'Deneme sınavları düzenliydi fakat sonuç analizleri geç geldi. Bu fiyata daha hızlı geri bildirim beklerdim.',
  ],
  mid: [
    'Öğretmen kadrosu genel olarak iyi, özellikle matematik tarafı güçlü. Bina biraz eski ama derslik düzeni yeterli.',
    'Deneme sınavı sıklığı ve soru kalitesi iyiydi. Rehberlik desteği ortalama, daha sık görüşme olsaydı daha iyi olurdu.',
    'Fiyat/performans olarak dengeli buldum. Kaynak kitapları pakete dahil olması ekstra masrafı azalttı.',
    'Ulaşımı kolay, etüt imkânı var. Kalabalık dönemlerde etüt sırası beklemek gerekebiliyor.',
    'Ders anlatımından memnunum, konu tekrarları düzenli. Taksit seçenekleri esnek olsaydı beş yıldız verirdim.',
  ],
  high: [
    'Sınıf mevcudu gerçekten söyledikleri gibiydi, öğretmenler soru sormaya açık. Yıl içinde netlerimde ciddi artış oldu.',
    'Rehberlik servisi tercih döneminde çok yardımcı oldu, süreci tek başımıza götürmek zorunda kalmadık.',
    'Etüt saatleri esnek ve gerçekten işliyor. Eksik konularda birebir destek alabildim, en çok bunu değerli buldum.',
    'Deneme analizleri detaylı, hangi konuya çalışmam gerektiğini net görebiliyordum. Kaynaklar da güncel.',
    'Veli olarak düzenli bilgilendirildim. Devamsızlık ve deneme sonuçları için iletişim çok düzenliydi.',
    'Fiyatı bölgedeki diğer kurumlara göre makul, aldığım desteğe değdi. Kayıt sürecinde de şeffaf davrandılar.',
  ],
};

/**
 * The 20 fictional institutions. Kept as data rather than generated so each one
 * reads like a plausible, distinct business rather than "Kurum 7".
 */
export const SEED_INSTITUTIONS: SeedInstitution[] = [
  {
    slug: 'ornek-akademi',
    name: 'Örnek Akademi',
    brand: 'Örnek Eğitim Grubu',
    type: 'DERSHANE',
    description:
      'YKS ve LGS hazırlık odaklı, sınıf mevcudunu 20 kişiyle sınırlayan bir hazırlık kurumu. Hafta içi akşam ve hafta sonu etüt programı sunuyor.',
    foundedYear: 2009,
    website: 'https://ornekakademi.example.com',
    phone: '+90 212 000 0001',
    isVerified: true,
    branches: [
      {
        name: 'Kadıköy Şubesi',
        city: 'İstanbul',
        district: 'Kadıköy',
        address: 'Örnek Mahallesi, Deneme Caddesi No: 12, Kadıköy',
        lat: 40.9903,
        lng: 29.0292,
        capacity: 420,
      },
      {
        name: 'Bakırköy Şubesi',
        city: 'İstanbul',
        district: 'Bakırköy',
        address: 'Numune Mahallesi, Örnek Sokak No: 5, Bakırköy',
        lat: 40.9819,
        lng: 28.8772,
        capacity: 310,
      },
    ],
    programs: [
      {
        name: 'YKS Sayısal Tam Zamanlı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 24,
        classSize: 18,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 96000,
        discountedPrice: 84000,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum web sitesi fiyat listesi, Eylül 2024',
      },
      {
        name: 'YKS Eşit Ağırlık Tam Zamanlı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 22,
        classSize: 20,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 92000,
        discountedPrice: 80000,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum web sitesi fiyat listesi, Eylül 2024',
      },
      {
        name: 'LGS Hafta Sonu',
        examType: 'LGS',
        targetGrade: '8. Sınıf',
        weeklyHours: 10,
        classSize: 16,
        durationMonths: 8,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 48000,
        discountedPrice: null,
        installmentCount: 6,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum web sitesi fiyat listesi, Eylül 2024',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'YKS',
        studentCount: 380,
        avgNetIncrease: 21.4,
        top1000Count: 6,
        placementRate: 72.5,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Kurumun kendi yayımladığı yıl sonu raporu',
        verified: false,
      },
      {
        academicYear: '2023-2024',
        examType: 'LGS',
        studentCount: 145,
        avgNetIncrease: 14.2,
        top1000Count: null,
        placementRate: 68.0,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Kurumun kendi yayımladığı yıl sonu raporu',
        verified: false,
      },
    ],
  },
  {
    slug: 'anadolu-kurs-merkezi',
    name: 'Anadolu Kurs Merkezi',
    brand: null,
    type: 'KURS_MERKEZI',
    description:
      'KPSS ve dil sınavlarına yoğunlaşan, yetişkin öğrenci profiline uygun esnek saatli kurs merkezi. Hafta sonu ve akşam grupları mevcut.',
    foundedYear: 2014,
    website: 'https://anadolukurs.example.com',
    phone: '+90 312 000 0002',
    isVerified: false,
    branches: [
      {
        name: 'Çankaya Şubesi',
        city: 'Ankara',
        district: 'Çankaya',
        address: 'Deneme Mahallesi, Kurgu Bulvarı No: 88, Çankaya',
        lat: 39.9208,
        lng: 32.8541,
        capacity: 260,
      },
    ],
    programs: [
      {
        name: 'KPSS Genel Yetenek - Genel Kültür',
        examType: 'KPSS',
        targetGrade: 'Mezun',
        weeklyHours: 16,
        classSize: 24,
        durationMonths: 6,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 38000,
        discountedPrice: 32000,
        installmentCount: 6,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum kayıt broşürü, Ağustos 2024',
      },
      {
        name: 'YDS Hazırlık',
        examType: 'DIL',
        targetGrade: 'Mezun',
        weeklyHours: 12,
        classSize: 18,
        durationMonths: 5,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 29000,
        discountedPrice: null,
        installmentCount: 4,
        priceSource: 'USER_REPORTED',
        priceSourceNote: 'Kayıt olan bir kullanıcının ilettiği sözleşme tutarı',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'KPSS',
        studentCount: 210,
        avgNetIncrease: 12.8,
        top1000Count: null,
        placementRate: null,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Kurum tanıtım sunumu',
        verified: false,
      },
    ],
  },
  {
    slug: 'zirve-egitim-kurumlari',
    name: 'Zirve Eğitim Kurumları',
    brand: 'Zirve Eğitim',
    type: 'DERSHANE',
    description:
      'Üç ilde şubesi bulunan, deneme sınavı analizine ağırlık veren hazırlık kurumu. Haftalık birebir rehberlik görüşmesi uyguluyor.',
    foundedYear: 2005,
    website: 'https://zirveegitim.example.com',
    phone: '+90 232 000 0003',
    isVerified: true,
    branches: [
      {
        name: 'Konak Şubesi',
        city: 'İzmir',
        district: 'Konak',
        address: 'Kurgu Mahallesi, Örnek Caddesi No: 40, Konak',
        lat: 38.4189,
        lng: 27.1287,
        capacity: 380,
      },
      {
        name: 'Bornova Şubesi',
        city: 'İzmir',
        district: 'Bornova',
        address: 'Deneme Mahallesi, Test Sokak No: 7, Bornova',
        lat: 38.4696,
        lng: 27.2166,
        capacity: 290,
      },
      {
        name: 'Nilüfer Şubesi',
        city: 'Bursa',
        district: 'Nilüfer',
        address: 'Örnek Mahallesi, Kurgu Caddesi No: 15, Nilüfer',
        lat: 40.2137,
        lng: 28.9634,
        capacity: 240,
      },
    ],
    programs: [
      {
        name: 'YKS Sayısal Tam Zamanlı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 26,
        classSize: 16,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 118000,
        discountedPrice: 105000,
        installmentCount: 10,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum web sitesi fiyat listesi, Eylül 2024',
      },
      {
        name: 'YKS Mezun Programı',
        examType: 'YKS',
        targetGrade: 'Mezun',
        weeklyHours: 30,
        classSize: 18,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 128000,
        discountedPrice: 112000,
        installmentCount: 10,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum web sitesi fiyat listesi, Eylül 2024',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'YKS',
        studentCount: 640,
        avgNetIncrease: 26.1,
        top1000Count: 14,
        placementRate: 81.3,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Kurumun yıl sonu başarı bülteni',
        verified: false,
      },
      {
        academicYear: '2022-2023',
        examType: 'YKS',
        studentCount: 590,
        avgNetIncrease: 24.7,
        top1000Count: 11,
        placementRate: 79.1,
        source: 'OSYM_PUBLIC',
        sourceNote: 'Örnek kamuya açık yerleştirme özeti (kurgusal veri)',
        verified: true,
      },
    ],
  },
  {
    slug: 'pusula-dershanesi',
    name: 'Pusula Dershanesi',
    brand: null,
    type: 'DERSHANE',
    description:
      'Küçük sınıf mevcuduyla çalışan mahalle ölçekli dershane. Öğrenci başına haftalık ödev takibi yapıyor.',
    foundedYear: 2016,
    website: 'https://pusuladershanesi.example.com',
    phone: '+90 322 000 0004',
    isVerified: false,
    branches: [
      {
        name: 'Seyhan Şubesi',
        city: 'Adana',
        district: 'Seyhan',
        address: 'Test Mahallesi, Numune Caddesi No: 23, Seyhan',
        lat: 37.0,
        lng: 35.3213,
        capacity: 180,
      },
    ],
    programs: [
      {
        name: 'YKS Sözel Tam Zamanlı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 20,
        classSize: 14,
        durationMonths: 8,
        includesMaterials: false,
        includesEtut: true,
        listPrice: 62000,
        discountedPrice: 55000,
        installmentCount: 8,
        priceSource: 'USER_REPORTED',
        priceSourceNote: 'Üç ayrı kullanıcının bildirdiği tutarların ortalaması',
      },
      {
        name: 'LGS Tam Zamanlı',
        examType: 'LGS',
        targetGrade: '8. Sınıf',
        weeklyHours: 14,
        classSize: 12,
        durationMonths: 8,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 44000,
        discountedPrice: null,
        installmentCount: 6,
        priceSource: 'ESTIMATED',
        priceSourceNote: 'Bölgedeki benzer programlardan tahmin edildi',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'LGS',
        studentCount: 86,
        avgNetIncrease: 16.5,
        top1000Count: null,
        placementRate: 74.4,
        source: 'USER_REPORTED',
        sourceNote: 'Veli anketiyle toplanan beyanlar',
        verified: false,
      },
    ],
  },
  {
    slug: 'bilgi-yolu-etut-merkezi',
    name: 'Bilgi Yolu Etüt Merkezi',
    brand: null,
    type: 'ETUT',
    description:
      'Ders anlatımı yerine birebir ve küçük grup etüdüne odaklanan merkez. Okul müfredatı takibi ve ödev desteği veriyor.',
    foundedYear: 2018,
    website: 'https://bilgiyolu.example.com',
    phone: '+90 262 000 0005',
    isVerified: false,
    branches: [
      {
        name: 'Merkez Şube',
        city: 'Eskişehir',
        district: 'Tepebaşı',
        address: 'Kurgu Mahallesi, Deneme Sokak No: 9, Tepebaşı',
        lat: 39.7767,
        lng: 30.5206,
        capacity: 120,
      },
    ],
    programs: [
      {
        name: 'LGS Etüt Programı',
        examType: 'LGS',
        targetGrade: '7-8. Sınıf',
        weeklyHours: 8,
        classSize: 6,
        durationMonths: 9,
        includesMaterials: false,
        includesEtut: true,
        listPrice: 36000,
        discountedPrice: 31000,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum kayıt sözleşmesi örneği, Eylül 2024',
      },
      {
        name: 'Ortaokul Genel Destek',
        examType: 'DIGER',
        targetGrade: '5-7. Sınıf',
        weeklyHours: 6,
        classSize: 8,
        durationMonths: 9,
        includesMaterials: false,
        includesEtut: true,
        listPrice: 27000,
        discountedPrice: null,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum kayıt sözleşmesi örneği, Eylül 2024',
      },
    ],
    performance: [],
  },
  {
    slug: 'nirvana-akademi',
    name: 'Nirvana Akademi',
    brand: null,
    type: 'DERSHANE',
    description:
      'Sayısal ağırlıklı programlarıyla bilinen, tıp ve mühendislik hedefleyen öğrencilere yönelik yoğun tempolu kurum.',
    foundedYear: 2011,
    website: 'https://nirvanaakademi.example.com',
    phone: '+90 216 000 0006',
    isVerified: true,
    branches: [
      {
        name: 'Ataşehir Şubesi',
        city: 'İstanbul',
        district: 'Ataşehir',
        address: 'Numune Mahallesi, Kurgu Caddesi No: 61, Ataşehir',
        lat: 40.9923,
        lng: 29.1244,
        capacity: 350,
      },
    ],
    programs: [
      {
        name: 'YKS Sayısal Yoğun Program',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 32,
        classSize: 14,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 142000,
        discountedPrice: 128000,
        installmentCount: 12,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat listesi, Eylül 2024',
      },
      {
        name: 'YKS Sayısal Mezun Yoğun',
        examType: 'YKS',
        targetGrade: 'Mezun',
        weeklyHours: 34,
        classSize: 12,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 156000,
        discountedPrice: 140000,
        installmentCount: 12,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat listesi, Eylül 2024',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'YKS',
        studentCount: 295,
        avgNetIncrease: 29.8,
        top1000Count: 22,
        placementRate: 88.2,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Kurum başarı bülteni',
        verified: false,
      },
    ],
  },
  {
    slug: 'kampus-online-egitim',
    name: 'Kampüs Online Eğitim',
    brand: null,
    type: 'ONLINE',
    description:
      'Tamamen çevrimiçi yürütülen, canlı ders ve kayıttan izleme imkânı sunan platform. Şubesi yok, tüm illerden katılım mümkün.',
    foundedYear: 2020,
    website: 'https://kampusonline.example.com',
    phone: '+90 850 000 0007',
    isVerified: false,
    branches: [
      {
        name: 'Online (Merkez Ofis)',
        city: 'İstanbul',
        district: 'Şişli',
        address: 'Kurgu Plaza, Deneme Caddesi No: 100, Şişli',
        lat: 41.0602,
        lng: 28.9877,
        capacity: 2000,
      },
    ],
    programs: [
      {
        name: 'YKS Online Tam Paket',
        examType: 'YKS',
        targetGrade: '12. Sınıf / Mezun',
        weeklyHours: 18,
        classSize: 60,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 34000,
        discountedPrice: 27000,
        installmentCount: 12,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Platform üzerindeki güncel paket fiyatı',
      },
      {
        name: 'LGS Online Tam Paket',
        examType: 'LGS',
        targetGrade: '8. Sınıf',
        weeklyHours: 12,
        classSize: 50,
        durationMonths: 8,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 22000,
        discountedPrice: 17500,
        installmentCount: 12,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Platform üzerindeki güncel paket fiyatı',
      },
      {
        name: 'KPSS Online Program',
        examType: 'KPSS',
        targetGrade: 'Mezun',
        weeklyHours: 14,
        classSize: 80,
        durationMonths: 6,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 15000,
        discountedPrice: null,
        installmentCount: 6,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Platform üzerindeki güncel paket fiyatı',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'YKS',
        studentCount: 1850,
        avgNetIncrease: 15.3,
        top1000Count: 4,
        placementRate: 61.7,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Platform yıllık değerlendirme yazısı',
        verified: false,
      },
    ],
  },
  {
    slug: 'meridyen-egitim-merkezi',
    name: 'Meridyen Eğitim Merkezi',
    brand: null,
    type: 'KURS_MERKEZI',
    description:
      'Dil sınavlarına ve yurt dışı başvuru süreçlerine odaklanan kurs merkezi. Küçük gruplarla konuşma pratiği ağırlıklı çalışıyor.',
    foundedYear: 2013,
    website: 'https://meridyenegitim.example.com',
    phone: '+90 242 000 0008',
    isVerified: false,
    branches: [
      {
        name: 'Muratpaşa Şubesi',
        city: 'Antalya',
        district: 'Muratpaşa',
        address: 'Örnek Mahallesi, Test Caddesi No: 31, Muratpaşa',
        lat: 36.8841,
        lng: 30.7056,
        capacity: 150,
      },
    ],
    programs: [
      {
        name: 'YDS / YÖKDİL Hazırlık',
        examType: 'DIL',
        targetGrade: 'Mezun',
        weeklyHours: 12,
        classSize: 14,
        durationMonths: 5,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 33000,
        discountedPrice: 28000,
        installmentCount: 5,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum kayıt broşürü, Eylül 2024',
      },
      {
        name: 'Genel İngilizce (B1-B2)',
        examType: 'DIGER',
        targetGrade: 'Tüm seviyeler',
        weeklyHours: 8,
        classSize: 12,
        durationMonths: 6,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 24000,
        discountedPrice: null,
        installmentCount: 6,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum kayıt broşürü, Eylül 2024',
      },
    ],
    performance: [],
  },
  {
    slug: 'atlas-dershanesi',
    name: 'Atlas Dershanesi',
    brand: 'Atlas Eğitim Grubu',
    type: 'DERSHANE',
    description:
      'Uzun süredir faaliyette olan, geniş kaynak arşivi ve düzenli deneme takvimiyle çalışan hazırlık kurumu.',
    foundedYear: 2001,
    website: 'https://atlasdershanesi.example.com',
    phone: '+90 332 000 0009',
    isVerified: true,
    branches: [
      {
        name: 'Selçuklu Şubesi',
        city: 'Konya',
        district: 'Selçuklu',
        address: 'Deneme Mahallesi, Kurgu Bulvarı No: 77, Selçuklu',
        lat: 37.8938,
        lng: 32.4932,
        capacity: 400,
      },
      {
        name: 'Meram Şubesi',
        city: 'Konya',
        district: 'Meram',
        address: 'Numune Mahallesi, Örnek Sokak No: 18, Meram',
        lat: 37.8451,
        lng: 32.4547,
        capacity: 220,
      },
    ],
    programs: [
      {
        name: 'YKS Eşit Ağırlık Tam Zamanlı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 24,
        classSize: 22,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 74000,
        discountedPrice: 66000,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat listesi, Ağustos 2024',
      },
      {
        name: 'LGS Tam Zamanlı',
        examType: 'LGS',
        targetGrade: '8. Sınıf',
        weeklyHours: 16,
        classSize: 20,
        durationMonths: 8,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 52000,
        discountedPrice: 46000,
        installmentCount: 8,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat listesi, Ağustos 2024',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'YKS',
        studentCount: 520,
        avgNetIncrease: 19.6,
        top1000Count: 5,
        placementRate: 70.2,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Kurum yıl sonu raporu',
        verified: false,
      },
    ],
  },
  {
    slug: 'panorama-akademi',
    name: 'Panorama Akademi',
    brand: null,
    type: 'KURS_MERKEZI',
    description:
      'Hafta sonu yoğunlaştırılmış programlarla çalışan, çalışan öğrencilere ve mezunlara yönelik kurs merkezi.',
    foundedYear: 2017,
    website: 'https://panoramaakademi.example.com',
    phone: '+90 342 000 0010',
    isVerified: false,
    branches: [
      {
        name: 'Şahinbey Şubesi',
        city: 'Gaziantep',
        district: 'Şahinbey',
        address: 'Kurgu Mahallesi, Deneme Caddesi No: 44, Şahinbey',
        lat: 37.0594,
        lng: 37.3825,
        capacity: 200,
      },
    ],
    programs: [
      {
        name: 'KPSS Hafta Sonu Programı',
        examType: 'KPSS',
        targetGrade: 'Mezun',
        weeklyHours: 12,
        classSize: 26,
        durationMonths: 6,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 29000,
        discountedPrice: 25000,
        installmentCount: 6,
        priceSource: 'USER_REPORTED',
        priceSourceNote: 'İki kullanıcının ilettiği kayıt tutarı',
      },
      {
        name: 'YKS Hafta Sonu Tekrar',
        examType: 'YKS',
        targetGrade: 'Mezun',
        weeklyHours: 14,
        classSize: 24,
        durationMonths: 7,
        includesMaterials: false,
        includesEtut: false,
        listPrice: 41000,
        discountedPrice: null,
        installmentCount: 7,
        priceSource: 'ESTIMATED',
        priceSourceNote: 'Benzer programların fiyat aralığından tahmin edildi',
      },
    ],
    performance: [],
  },
  {
    slug: 'prizma-etut-merkezi',
    name: 'Prizma Etüt Merkezi',
    brand: null,
    type: 'ETUT',
    description:
      'Birebir etüt ve küçük grup çalışmasıyla eksik konu tamamlamaya odaklanan merkez. Saatlik paket seçenekleri sunuyor.',
    foundedYear: 2019,
    website: 'https://prizmaetut.example.com',
    phone: '+90 224 000 0011',
    isVerified: false,
    branches: [
      {
        name: 'Osmangazi Şubesi',
        city: 'Bursa',
        district: 'Osmangazi',
        address: 'Test Mahallesi, Numune Sokak No: 3, Osmangazi',
        lat: 40.1885,
        lng: 29.061,
        capacity: 90,
      },
    ],
    programs: [
      {
        name: 'YKS Birebir Etüt Paketi',
        examType: 'YKS',
        targetGrade: '11-12. Sınıf',
        weeklyHours: 6,
        classSize: 3,
        durationMonths: 6,
        includesMaterials: false,
        includesEtut: true,
        listPrice: 58000,
        discountedPrice: null,
        installmentCount: 6,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat tarifesi, Ekim 2024',
      },
      {
        name: 'LGS Birebir Etüt Paketi',
        examType: 'LGS',
        targetGrade: '8. Sınıf',
        weeklyHours: 5,
        classSize: 2,
        durationMonths: 6,
        includesMaterials: false,
        includesEtut: true,
        listPrice: 49000,
        discountedPrice: 44000,
        installmentCount: 6,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat tarifesi, Ekim 2024',
      },
    ],
    performance: [],
  },
  {
    slug: 'ufuk-cizgisi-egitim',
    name: 'Ufuk Çizgisi Eğitim',
    brand: null,
    type: 'DERSHANE',
    description:
      'Rehberlik ve motivasyon çalışmalarını programın merkezine koyan, veli bilgilendirmesine önem veren hazırlık kurumu.',
    foundedYear: 2012,
    website: 'https://ufukcizgisi.example.com',
    phone: '+90 352 000 0012',
    isVerified: false,
    branches: [
      {
        name: 'Kocasinan Şubesi',
        city: 'Kayseri',
        district: 'Kocasinan',
        address: 'Örnek Mahallesi, Kurgu Caddesi No: 26, Kocasinan',
        lat: 38.7359,
        lng: 35.4787,
        capacity: 230,
      },
    ],
    programs: [
      {
        name: 'YKS Sayısal Tam Zamanlı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 22,
        classSize: 20,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 68000,
        discountedPrice: 61000,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum kayıt broşürü, Eylül 2024',
      },
      {
        name: 'LGS Tam Zamanlı',
        examType: 'LGS',
        targetGrade: '8. Sınıf',
        weeklyHours: 15,
        classSize: 18,
        durationMonths: 8,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 45000,
        discountedPrice: null,
        installmentCount: 8,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum kayıt broşürü, Eylül 2024',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'YKS',
        studentCount: 175,
        avgNetIncrease: 17.9,
        top1000Count: 1,
        placementRate: 66.8,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Kurum tanıtım broşürü',
        verified: false,
      },
    ],
  },
  {
    slug: 'denge-akademi',
    name: 'Denge Akademi',
    brand: null,
    type: 'KURS_MERKEZI',
    description:
      'Okul destek dersleri ve sınav hazırlığını birlikte yürüten kurs merkezi. Ders saatleri okul çıkışına göre planlanıyor.',
    foundedYear: 2015,
    website: 'https://dengeakademi.example.com',
    phone: '+90 232 000 0013',
    isVerified: false,
    branches: [
      {
        name: 'Karşıyaka Şubesi',
        city: 'İzmir',
        district: 'Karşıyaka',
        address: 'Deneme Mahallesi, Örnek Sokak No: 55, Karşıyaka',
        lat: 38.4615,
        lng: 27.1177,
        capacity: 170,
      },
    ],
    programs: [
      {
        name: 'YKS Eşit Ağırlık Destek',
        examType: 'YKS',
        targetGrade: '11-12. Sınıf',
        weeklyHours: 12,
        classSize: 16,
        durationMonths: 8,
        includesMaterials: false,
        includesEtut: true,
        listPrice: 47000,
        discountedPrice: 42000,
        installmentCount: 8,
        priceSource: 'USER_REPORTED',
        priceSourceNote: 'Bir kullanıcının paylaştığı kayıt sözleşmesi',
      },
      {
        name: 'Lise Genel Destek',
        examType: 'DIGER',
        targetGrade: '9-10. Sınıf',
        weeklyHours: 8,
        classSize: 14,
        durationMonths: 9,
        includesMaterials: false,
        includesEtut: true,
        listPrice: 31000,
        discountedPrice: null,
        installmentCount: 9,
        priceSource: 'ESTIMATED',
        priceSourceNote: 'Benzer programlardan tahmin edildi',
      },
    ],
    performance: [],
  },
  {
    slug: 'kuzey-yildizi-dershanesi',
    name: 'Kuzey Yıldızı Dershanesi',
    brand: null,
    type: 'DERSHANE',
    description:
      'Yatılı ve gündüzlü seçenek sunan, il dışından gelen öğrencilere barınma desteği sağlayan hazırlık kurumu.',
    foundedYear: 2008,
    website: 'https://kuzeyyildizi.example.com',
    phone: '+90 462 000 0014',
    isVerified: true,
    branches: [
      {
        name: 'Ortahisar Şubesi',
        city: 'Trabzon',
        district: 'Ortahisar',
        address: 'Kurgu Mahallesi, Test Caddesi No: 12, Ortahisar',
        lat: 41.0015,
        lng: 39.7178,
        capacity: 300,
      },
    ],
    programs: [
      {
        name: 'YKS Sayısal Tam Zamanlı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 26,
        classSize: 19,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 88000,
        discountedPrice: 79000,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat listesi, Eylül 2024',
      },
      {
        name: 'YKS Mezun Programı',
        examType: 'YKS',
        targetGrade: 'Mezun',
        weeklyHours: 28,
        classSize: 21,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 94000,
        discountedPrice: null,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat listesi, Eylül 2024',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'YKS',
        studentCount: 260,
        avgNetIncrease: 22.3,
        top1000Count: 3,
        placementRate: 75.9,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Kurum başarı sayfası',
        verified: false,
      },
    ],
  },
  {
    slug: 'sarmal-online-kurs',
    name: 'Sarmal Online Kurs',
    brand: null,
    type: 'ONLINE',
    description:
      'Kayıttan izleme ağırlıklı, düşük fiyatlı çevrimiçi kurs. Canlı ders yerine soru çözüm seansları düzenliyor.',
    foundedYear: 2021,
    website: 'https://sarmalonline.example.com',
    phone: '+90 850 000 0015',
    isVerified: false,
    branches: [
      {
        name: 'Online (Merkez Ofis)',
        city: 'Ankara',
        district: 'Yenimahalle',
        address: 'Deneme İş Merkezi, Kurgu Caddesi No: 210, Yenimahalle',
        lat: 39.9727,
        lng: 32.7594,
        capacity: 1500,
      },
    ],
    programs: [
      {
        name: 'YKS Online Konu Anlatım Paketi',
        examType: 'YKS',
        targetGrade: '11-12. Sınıf / Mezun',
        weeklyHours: 10,
        classSize: 120,
        durationMonths: 12,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 12000,
        discountedPrice: 8900,
        installmentCount: 12,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Platform kampanya sayfası, Ekim 2024',
      },
      {
        name: 'LGS Online Konu Anlatım Paketi',
        examType: 'LGS',
        targetGrade: '8. Sınıf',
        weeklyHours: 8,
        classSize: 120,
        durationMonths: 10,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 9500,
        discountedPrice: 6900,
        installmentCount: 10,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Platform kampanya sayfası, Ekim 2024',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'YKS',
        studentCount: 940,
        avgNetIncrease: 9.8,
        top1000Count: null,
        placementRate: 52.4,
        source: 'USER_REPORTED',
        sourceNote: 'Kullanıcı anketi beyanları',
        verified: false,
      },
    ],
  },
  {
    slug: 'terazi-egitim-kurumlari',
    name: 'Terazi Eğitim Kurumları',
    brand: 'Terazi Eğitim',
    type: 'DERSHANE',
    description:
      'Sayısal, eşit ağırlık ve sözel alanların üçünde de tam zamanlı program yürüten, orta ölçekli hazırlık kurumu.',
    foundedYear: 2010,
    website: 'https://terazegitim.example.com',
    phone: '+90 312 000 0016',
    isVerified: false,
    branches: [
      {
        name: 'Keçiören Şubesi',
        city: 'Ankara',
        district: 'Keçiören',
        address: 'Numune Mahallesi, Deneme Caddesi No: 91, Keçiören',
        lat: 39.9819,
        lng: 32.8639,
        capacity: 280,
      },
      {
        name: 'Mamak Şubesi',
        city: 'Ankara',
        district: 'Mamak',
        address: 'Örnek Mahallesi, Kurgu Sokak No: 14, Mamak',
        lat: 39.9264,
        lng: 32.9092,
        capacity: 190,
      },
    ],
    programs: [
      {
        name: 'YKS Sayısal Tam Zamanlı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 23,
        classSize: 21,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 71000,
        discountedPrice: 64000,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat listesi, Eylül 2024',
      },
      {
        name: 'YKS Sözel Tam Zamanlı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 21,
        classSize: 23,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: false,
        listPrice: 67000,
        discountedPrice: 60000,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat listesi, Eylül 2024',
      },
      {
        name: 'LGS Hafta Sonu',
        examType: 'LGS',
        targetGrade: '8. Sınıf',
        weeklyHours: 9,
        classSize: 22,
        durationMonths: 8,
        includesMaterials: false,
        includesEtut: false,
        listPrice: 33000,
        discountedPrice: null,
        installmentCount: 8,
        priceSource: 'USER_REPORTED',
        priceSourceNote: 'Bir velinin ilettiği kayıt tutarı',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'YKS',
        studentCount: 410,
        avgNetIncrease: 18.2,
        top1000Count: 2,
        placementRate: 69.4,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Kurum yıl sonu bülteni',
        verified: false,
      },
    ],
  },
  {
    slug: 'adim-adim-etut-merkezi',
    name: 'Adım Adım Etüt Merkezi',
    brand: null,
    type: 'ETUT',
    description:
      'İlkokul ve ortaokul seviyesinde ödev takibi, okuma alışkanlığı ve temel beceri çalışmaları yürüten etüt merkezi.',
    foundedYear: 2020,
    website: 'https://adimadimetut.example.com',
    phone: '+90 216 000 0017',
    isVerified: false,
    branches: [
      {
        name: 'Maltepe Şubesi',
        city: 'İstanbul',
        district: 'Maltepe',
        address: 'Test Mahallesi, Örnek Caddesi No: 8, Maltepe',
        lat: 40.9351,
        lng: 29.1552,
        capacity: 110,
      },
    ],
    programs: [
      {
        name: 'Ortaokul Etüt ve Ödev Takibi',
        examType: 'DIGER',
        targetGrade: '5-8. Sınıf',
        weeklyHours: 10,
        classSize: 10,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 39000,
        discountedPrice: 35000,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat tarifesi, Eylül 2024',
      },
      {
        name: 'LGS Destek Etüdü',
        examType: 'LGS',
        targetGrade: '8. Sınıf',
        weeklyHours: 7,
        classSize: 8,
        durationMonths: 8,
        includesMaterials: false,
        includesEtut: true,
        listPrice: 34000,
        discountedPrice: null,
        installmentCount: 8,
        priceSource: 'ESTIMATED',
        priceSourceNote: 'Bölgedeki etüt merkezlerinin ortalamasından tahmin edildi',
      },
    ],
    performance: [],
  },
  {
    slug: 'vektor-akademi',
    name: 'Vektör Akademi',
    brand: null,
    type: 'KURS_MERKEZI',
    description:
      'Matematik ve fen bilimleri branşlarında yoğunlaşmış, soru çözüm kampları düzenleyen kurs merkezi.',
    foundedYear: 2018,
    website: 'https://vektorakademi.example.com',
    phone: '+90 258 000 0018',
    isVerified: false,
    branches: [
      {
        name: 'Merkezefendi Şubesi',
        city: 'Denizli',
        district: 'Merkezefendi',
        address: 'Kurgu Mahallesi, Numune Caddesi No: 47, Merkezefendi',
        lat: 37.7833,
        lng: 29.0833,
        capacity: 160,
      },
    ],
    programs: [
      {
        name: 'YKS Matematik Branş Programı',
        examType: 'YKS',
        targetGrade: '11-12. Sınıf / Mezun',
        weeklyHours: 8,
        classSize: 15,
        durationMonths: 7,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 36000,
        discountedPrice: 32000,
        installmentCount: 7,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum web sitesi, Eylül 2024',
      },
      {
        name: 'YKS Fen Bilimleri Branş Programı',
        examType: 'YKS',
        targetGrade: '11-12. Sınıf / Mezun',
        weeklyHours: 9,
        classSize: 15,
        durationMonths: 7,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 38000,
        discountedPrice: 34000,
        installmentCount: 7,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum web sitesi, Eylül 2024',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'YKS',
        studentCount: 190,
        avgNetIncrease: 11.4,
        top1000Count: null,
        placementRate: null,
        source: 'USER_REPORTED',
        sourceNote: 'Öğrenci beyanlarından derlendi',
        verified: false,
      },
    ],
  },
  {
    slug: 'berrak-egitim-merkezi',
    name: 'Berrak Eğitim Merkezi',
    brand: null,
    type: 'KURS_MERKEZI',
    description:
      'Sınav kaygısı yönetimi ve çalışma planı oluşturma atölyelerini programına dahil eden kurs merkezi.',
    foundedYear: 2016,
    website: 'https://berrakegitim.example.com',
    phone: '+90 288 000 0019',
    isVerified: false,
    branches: [
      {
        name: 'Merkez Şube',
        city: 'Edirne',
        district: 'Merkez',
        address: 'Örnek Mahallesi, Deneme Sokak No: 21, Merkez',
        lat: 41.6771,
        lng: 26.5557,
        capacity: 130,
      },
    ],
    programs: [
      {
        name: 'YKS Eşit Ağırlık Programı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 18,
        classSize: 17,
        durationMonths: 8,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 54000,
        discountedPrice: 48000,
        installmentCount: 8,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum kayıt broşürü, Eylül 2024',
      },
      {
        name: 'LGS Programı',
        examType: 'LGS',
        targetGrade: '8. Sınıf',
        weeklyHours: 12,
        classSize: 15,
        durationMonths: 8,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 41000,
        discountedPrice: 37000,
        installmentCount: 8,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum kayıt broşürü, Eylül 2024',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'LGS',
        studentCount: 72,
        avgNetIncrease: 13.6,
        top1000Count: null,
        placementRate: 71.1,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Kurum bilgilendirme yazısı',
        verified: false,
      },
    ],
  },
  {
    slug: 'yorunge-dershanesi',
    name: 'Yörünge Dershanesi',
    brand: null,
    type: 'DERSHANE',
    description:
      'Bire bir koçluk sistemi ve haftalık çalışma programı takibiyle çalışan, orta ölçekli hazırlık kurumu.',
    foundedYear: 2013,
    website: 'https://yorungedershanesi.example.com',
    phone: '+90 264 000 0020',
    isVerified: false,
    branches: [
      {
        name: 'Adapazarı Şubesi',
        city: 'Sakarya',
        district: 'Adapazarı',
        address: 'Deneme Mahallesi, Kurgu Caddesi No: 63, Adapazarı',
        lat: 40.7808,
        lng: 30.4033,
        capacity: 210,
      },
    ],
    programs: [
      {
        name: 'YKS Sayısal Tam Zamanlı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 25,
        classSize: 18,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 79000,
        discountedPrice: 71000,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat listesi, Eylül 2024',
      },
      {
        name: 'YKS Eşit Ağırlık Tam Zamanlı',
        examType: 'YKS',
        targetGrade: '12. Sınıf',
        weeklyHours: 23,
        classSize: 19,
        durationMonths: 9,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 76000,
        discountedPrice: 68000,
        installmentCount: 9,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat listesi, Eylül 2024',
      },
      {
        name: 'LGS Tam Zamanlı',
        examType: 'LGS',
        targetGrade: '8. Sınıf',
        weeklyHours: 14,
        classSize: 16,
        durationMonths: 8,
        includesMaterials: true,
        includesEtut: true,
        listPrice: 47000,
        discountedPrice: null,
        installmentCount: 8,
        priceSource: 'OFFICIAL',
        priceSourceNote: 'Kurum fiyat listesi, Eylül 2024',
      },
    ],
    performance: [
      {
        academicYear: '2023-2024',
        examType: 'YKS',
        studentCount: 230,
        avgNetIncrease: 20.1,
        top1000Count: 2,
        placementRate: 73.6,
        source: 'INSTITUTION_CLAIM',
        sourceNote: 'Kurum yıl sonu raporu',
        verified: false,
      },
    ],
  },
];
